- package-lock.json
- tooling/cli/lib/validations.js
Closes CLM-5218
Currently, the cli authentication operation validates given TI instance against endpoint `/incoming/v2/ping`. Change it to validate against helium endpoint over `CompanyDetails` query.
To verify, not sure what's the best way to verify the changes outside the context of helium demo app. Did the following sanity checks:
- in helium repo, verify the cli authentication operation directly with both a valid and an invalid api key. 
- in stackblitz project referencing the workspace `tooling/cli` (could follow [this link](https://stackblitz.com/fork/github/thoughtindustries/helium/tree/update-cli-auth/tooling/cli)), verify the cli authentication operation directly with a combination of feature flag `Allow Stackblitz for Helium`, and valid/invalid api keys. It is interesting to …
> feat: update cli authentication operation

- tooling/template-base/components/CatalogAndAggreg/CatalogAndAggregation.tsx
- tooling/template-base/components/CatalogAndAggreg/CatalogError.tsx
Unticketed
An issue occurred when loading catalog page of the helium app. The page did quick flash from content to blank page and the console shows error about missing catalog context. Can repro this in helium app script, but not able to repro from helium template base workspace.
think the culprit might lie in how vite scanned and bundled the assets when importing from package files source directly (instead of from the package entry point). As noted the console error for missing Catalog Context in the browser, it shows the error stack from `CatalogProvider` (vite bundled asset) to `CatalogError` (not bundled by vite).
This could cause the `CatalogError` to access a different context object than the one populated by `CatalogProvider`. changes to fix this: Instead of importing from package …
> feat: use local catalog error component

- tooling/helium-server/worker/ssr.js
In `@thoughtindustries/helium-server`, remove the closing angle bracket from regex pattern/replace in `resolveAssetUrls` to account for additional attributes in elements.
> fix: remove closing angle bracket from regex match

- package-lock.json
- packages/cart/package.json
- packages/catalog/package.json
- packages/contact-block/package.json
- packages/content/package.json
- packages/dashboard-stats/package.json
- packages/featured-content/package.json
- packages/header/package.json
- packages/hero/package.json
- packages/hooks/package.json
- packages/link-lists/package.json
- packages/navigation-bar/package.json
- packages/pagination/package.json
- packages/testimonial/package.json
- packages/user/package.json
- packages/video-player/package.json
- tooling/cli/package.json
- tooling/template-base/package.json
Closes CLM-6029
Since the release for CLM-6029, we now have packages targeting different distribution tags (`latest` vs `beta`) in the monorepo. To simplify the updated package release process, we could add `tag` under `publishConfig` for pre-released packages, the default `tag` will target `latest` for stable releases.
> feat: add dist tag

- tooling/helium-server/src/utilities/init-page-context.ts
Closes CLM-6860
The `UserAwardCount` returns an object with the associated `awardType.id` as its `id` instead of the `id` of the `award` itself. If the same `awardType` is used across multiple courses, then requests that contain multiple `UserCourseAwardCounts` can have returns that are cached versions of the first return due to Apollo Client defaulting to the `objectType`'s `id` as the cache key.
This change modifies the type policy to use `['id', 'label', 'count']` as the cache key instead.
Additional Reading: https://www.apollographql.com/docs/react/caching/cache-configuration/#customizing-cache-ids
> fix: set custom cache key for UserAwardCount type objects

- tooling/cli/lib/deploy.js
Closes CLM-7704
Sets `duplex` option when using a stream for request body.
Add'l Reading: https://github.com/nodejs/node/issues/46221
> CLM-7704 Set duplex option when using stream as body in request

- tooling/cli/lib/command-modules/authenticate.js
- tooling/cli/lib/command-modules/deploy.js
- tooling/cli/lib/deploy.js
- tooling/cli/lib/deployment-log.js
- tooling/cli/lib/helpers/prompts.js
- tooling/cli/lib/prompts.js
Closes CLM-7218
This is a draft to add cli function to fetch deploy log when deployment fails. Referring to the current structure, we handle the deploy cli command in the command module and spawns a shell to run the deploy script. Since deployment could fail at different stage and we want to only prompt user for fetching the log when batch job fails, might consider a communication between the deploy command module and spawned deploy process. 
I am using the following structure to establish communications between processes:
- parent process: the deploy cli command module (`./lib/command-modules/deploy.js`) is responsible for the cli command declaration, orchestrating spawning/closing child processes, and prompting user questions.
- child deployment process: the spawned deploy process …
> feat: add cli function to fetch deploy log when deployment fails

- tooling/helium-server/src/server/server.ts
Closes CLM-8345
SSO users cannot use the `Login` mutation as no password is set, and the `/access/` endpoints in the Thought Industries platform sets auth cookies for their respective domain, so they're not included in `localhost` requests.
> fix: append ti-config user to request body in local dev

- tooling/tailwind-preset/src/index.ts
- tooling/template-base-essentials/tailwind.config.js
- tooling/template-base/tailwind.config.js
Closes CLM-8429
Paths aren't relative to `tailwind.config.js`. While a `relative` option was added in v3.2, if a user decides to specify their own `content` directory, tailwindcss's preset behavior will overwrite the `content` specified in our preset.
> fix: move content paths to template tailwind config

- tooling/helium-server/src/server/server.ts
Extends #198 
When testing the original PR, was using `/graphiql` which was sending the queries as single objects. Queries in components can be batched, in which case `user` was not being appended to `reqBody<Array>` correctly.
> fix: batched queries compatibility issue setting user in local dev

- tooling/helium-server/src/server/server.ts
- tooling/helium-server/worker/ssr.js
- tooling/template-base-essentials/renderer/_default.page.server.tsx
- tooling/template-base/renderer/_default.page.server.tsx
Closes CLM-8453
A recent update `vite-plugin-ssr` created a new export path for modules used on the server side, outputting the below warning:
```
Error: [vite-plugin-ssr@0.4.115][Warning] You have following imports which are outdated:
import { something } from 'vite-plugin-ssr'
Replace them with:
import { something } from 'vite-plugin-ssr/server'
Or if `something` is a type:
import type { something } from 'vite-plugin-ssr/types'
Make sure to import renderPage(), escapeInject, html, dangerouslySkipEscape(), pipeWebStream(), pipeNodeStream(), pipeStream(), stampPipe() from 'vite-plugin-ssr/server'. (Or inspect the error stack below to find the import causing this warning.)
```
Project still built fine, but no one likes a warning and trace in their terminal.
> refactor: update vite-plugin-ssr server side import statements

- tooling/create-helium-app/package.json
Unticketed; adds `template-base-essentials` to files included in published `create-helium-app` package.
> fix: add template-base-essentials to package.json files

- packages/catalog/__tests__/catalog.test.tsx
- packages/catalog/src/catalog-aggregations.tsx
- packages/catalog/src/variants/display-type-results/item-queue-button.tsx
- packages/pagination/__tests__/pagination.test.tsx
- packages/pagination/src/pagination.tsx
Closes CLM-8852
Hydration mismatch was appearing when catalog component was being rendered. This was caused by issues with white space and code formatting. This has been resolved by computing the string instead. 
This ticket makes changes to the catalog package, along with the pagination package which is used in the catalog component.
Also ran `npm test -- -u` to update screenshots
> CLM-8852 Remove Hydration Error on Catalog Component

- .storybook/main.ts
- package-lock.json
- package.json
- packages/catalog/stories/Catalog.stories.tsx
- packages/dashboard-stats/stories/DashboardStats.stories.tsx
- packages/featured-content/stories/FeaturedContentWithDataFetching.stories.tsx
- tooling/storybook-addon-apollo-client/src/index.tsx
Closes CLM-8880
Re-enable story source addon in latest stable version of storybook. With the latest component story format (CSF3), the addon seems to only render the object for exported story. The format of the story source seems pretty straightforward for simple UI component (like: Hero component). For complex component like the Catalog component, the stories were written with a template component to be re-usable for multiple stories, the story source only renders the template component which does not seem very clear how the template component is written. Made some adjustments to the stories. Attached below for a sample story with story source:
> feat: add story source

- packages/catalog/__tests__/catalog.test.tsx
- packages/catalog/src/variants/display-type-results/calendar.tsx
- packages/catalog/src/variants/display-type-results/grid.tsx
- packages/catalog/src/variants/display-type-results/list.tsx
- tooling/tailwind-preset/src/index.ts
- tooling/template-base-essentials/renderer/tailwind.css
- tooling/template-base/renderer/tailwind.css
Closes CLM-8876
Catalog component uses Tailwind visibility utility classes to toggle the display for dropdown menu. The ones used are `visible` and `invisible`. When the visibility utility is disabled in tailwind config, tailwind will not generate any classes for this utility. This would cause the dropdown menu to be unresponsive in catalog component. The reason to disable the visibility utility is to avoid class name conflicts between tailwind and TI core platform (for example, the `collapse` class name), this conflict applies more likely to a TI core platform page with Atoms deployed currently. The conflict is not a concern for helium page.
To make sure catalog component to continue function on helium pages, will update the tailwind preset package to add custom utilities for `visible` …
> fix: catalog component malfunctioning

- package-lock.json
- packages/cart/__tests__/core/components/cart-provider/utilities.test.ts
- packages/cart/package.json
- packages/cart/src/core/components/cart-provider/use-persist-reducer.ts
- packages/cart/src/core/components/cart-provider/utilities.ts
Closes CLM-8820
changes:
- set cart cookie to path `/`
- override default encoder in `universal-cookie` when serializing cart cookie value
- currently the serialization/parsing of cookie value is handled by `window.atob` and `window.btoa`, which seems to work fine except for the handling of non-binary data. Replace it with `buffer` package to simulate node's `Buffer` API for browser.
verifications: deployed a test helium app along with some tweaks to the staging environment. The helium app only contains a dynamic path for '/courses/@courseSlug' which handles the cart rendering for ILT contents. Setup some ILT contents for purchase in staging. Verify the cart to be synced between the helium page and non-helium page. 
notes: helium feature flag is turned of in staging to avoid testing …
> fix: cart issues

- package-lock.json
- tooling/cli/lib/deploy.js
- tooling/cli/lib/file-generators.js
- tooling/cli/lib/helpers/constants.js
- tooling/cli/lib/helpers/filepaths.js
- tooling/cli/package.json
Closes CLM-9414
- Adds a `content` property to the generated `ti-config.json` with default `pages` and `components` value.
- When using the `deploy` command, all project paths will be gathered, then filtered against paths stored in `ti-config.content`.
- Resulting array of paths is `concat` w/ `node_modules/@thoughtindustries`, and the final array is used to pluck GraphQL operations.
> Feat: Allow configuring paths for plucked GraphQL Operations

- package-lock.json
- tooling/template-base-essentials/package.json
- tooling/template-base/package.json
Closes CLM-10059
In version `0.4.142`, `vite-plugin-ssr` was renamed to `vike`. Since our `package.json` ships with the dependency set to `^0.4.43`, more recent installs could end up with` 0.4.142` and – unless some text-replacements are completed (see [[1]](https://vite-plugin-ssr.com/vike) and[[2]](https://github.com/vikejs/vike/discussions/1147#discussioncomment-7112677)) - the project could be compiled without a `/dist/client/manifest.json` and cause deployments to fail.
> Fix: pin vite-plugin-ssr version

- tooling/cli/README.md
- tooling/cli/lib/command-modules/deploy.js
- tooling/cli/lib/deploy.js
- tooling/cli/lib/file-generators.js
- tooling/template-base-essentials/package.json
- tooling/template-base/package.json
Closes CLM-10089
This change allows users to pass a `-d`/`-debug` flag when running `helium deploy`/`npm run deploy` in order to deploy a development build to assist troubleshooting efforts.
In order to do so, users will need to a `.env.development` file with `NODE_ENV='development'`.
> feat: allow deployment of development builds

- tooling/cli/lib/deploy.js
Fixes CLM-10089
`DEVELOPMENT_BUILD` ends up getting passed as a string in `process.env`. This change fixes the check where we verify if the development build flag was passed.
> fix: fix check where development build env var assigned as string

- tooling/cli/lib/deploy.js
- tooling/cli/lib/helpers/atoms.js
- tooling/cli/lib/helpers/filepaths.js
Continues CLM-10089
- Moves `getFileContents` from `/helpers/atoms` to more appropriate `/helpers/filepaths`.
- Updates `deploy` command to temporarily rename `.env.development` to `.env` when deploying development builds, with the files resetting after upload.
> fix: temporarily rename env files when using development build commands

- tooling/helium-server/worker/ssr.js
Closes CLM-10925
Adds check for `HELIUM_PRIVATE_ENABLE_ASSET_PROXY` env var. 
If `HELIUM_PRIVATE_ENABLE_ASSET_PROXY=true`, we'll leave asset URLs as written and proxy through Thought Industries backend.
> feat: add check for HELIUM_PRIVATE_ENABLE_ASSET_PROXY

- tooling/helium-server/worker/ssr.js
Removes check for `HELIUM_PRIVATE_ENABLE_ASSET_PROXY` env variable and instead proxies all requests through TI
> feat: make asset proxy permanent
